### ISSUE TITLE
Missing files while compiling

### ISSUE THREAD

**Issue by RoySimons96** [nloyfer/wgbs_tools#26]
I got an error that the files: 'homog.o', 'homog' and 'main.o' were missing when compiling.
After downloading those files from an old branch (https://github.com/nloyfer/wgbs_tools/tree/e83804a101526d5ddda4837ec56c22b667a50dce/src/homog) I was able to successfully compile wgbstools.

**Comment by nloyfer** [comment]
Thank you.
I removed them on purpose, because I think it's best that each user compiles their own binaries.
You can use these old binaries, they probably work just fine. But The better way to solve this is to find out why you weren't able to compile `homog` on your end. My guess is that you don't have `boost` installed (see issue #27), which I have now resolved.
