### ISSUE TITLE
Supplementary Data: Extended Tables 

### ISSUE THREAD

**Issue by Jonbroad15** [nloyfer/wgbs_tools#5]
Hi,

Can you please point me towards the extended tables S1-S5 mentioned in your [paper](https://www.biorxiv.org/content/10.1101/2022.01.24.477547v1)

I cannot seem to find them on bioarXiv

**Comment by nloyfer** [comment]
Hi,

The unpublished version on biorxiv is incomplete and does not contain the supplementary data.
The supplementary data will only be available in the published version. I will update the readme here as soon as that happens.

Since this issue is unrelated to the wgbs_tools package I am closing it, but feel free to email me with any further questions about the biorxiv paper!

Regards
