### ISSUE TITLE
beta_to_450k update

### ISSUE THREAD

**Issue by JBinkowski** [nloyfer/wgbs_tools#9]
Dear Author,
Could You please update the reference used in beta_to_450k script, to work with Illumina EPIC data?

**Comment by nloyfer** [comment]
Hi,
Absolutely.
I updated `wgbstools beta_to_450k` to include all 850K EPIC sites.
If you provide a user site reference file (`--ref` flag) that includes sites from EPIC, they will now be included in the output.
If you don't provide your own reference file, you have to set the `--EPIC` flag, so that all ~850K sites will be included, instead of 450K.

I also added beta_to_450k support for hg38.

Let me know if it works for you

**Comment by JBinkowski** [comment]
Yes, it works!
Thanks for upgrade.
